"""
Tests for the scrub-text and scrub-file CLI subcommands (Feature 5:
legitimate hygiene reframing).

The scrub subcommands are the hygiene-only path: they strip invisible
Unicode and AI-attribution comments / file metadata, but they do NOT
humanize or perturb statistical AI vocabulary. They require an explicit
--i-own-this-content confirmation flag.
"""

import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from aphanis.cleaner import clean_text


REPO_ROOT = Path(__file__).resolve().parent.parent
PYTHON = sys.executable

# ZWSP family: use chr() to avoid having actual control chars in the
# source file, which get mangled by editors and copy-paste.
ZWSP = chr(0x200B)
ZWNJ = chr(0x200C)
ZWJ = chr(0x200D)
BOM = chr(0xFEFF)


def run_aphanis(args, stdin=None):
    """Run `python -m aphanis.cli <args>` and return CompletedProcess."""
    return subprocess.run(
        [PYTHON, "-m", "aphanis.cli", *args],
        capture_output=True,
        text=True,
        input=stdin,
        cwd=str(REPO_ROOT),
    )


class TestScrubTextHygiene(unittest.TestCase):
    """scrub-text must strip invisible Unicode + AI comments, but not humanize."""

    def test_strips_zero_width_chars(self):
        result = run_aphanis(
            ["scrub-text", "--i-own-this-content"],
            stdin=f"Hello world{ZWJ}with{ZWNJ}zero{BOM}width chars.",
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        # Zero-width family gone
        self.assertNotIn(ZWSP, result.stdout)
        self.assertNotIn(ZWNJ, result.stdout)
        self.assertNotIn(ZWJ, result.stdout)
        self.assertNotIn(BOM, result.stdout)
        # Visible text preserved
        self.assertIn("Hello world", result.stdout)
        self.assertIn("with", result.stdout)
        self.assertIn("zero", result.stdout)
        self.assertIn("width", result.stdout)
        self.assertIn("chars", result.stdout)

    def test_strips_ai_comments(self):
        result = run_aphanis(
            ["scrub-text", "--i-own-this-content"],
            stdin="# Generated by Claude\ndef hello(): return 1\n",
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertNotIn("Generated by Claude", result.stdout)
        self.assertIn("def hello()", result.stdout)

    def test_does_not_humanize(self):
        original = "Furthermore, we must consider the implications."
        result = run_aphanis(
            ["scrub-text", "--i-own-this-content"],
            stdin=original,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        # Hygiene should not run humanize: "we must" should pass through
        # unchanged (humanizer would rewrite it).
        self.assertIn("Furthermore", result.stdout)
        self.assertIn("we must", result.stdout)
        self.assertIn("consider", result.stdout)

    def test_does_not_perturb_ai_vocabulary(self):
        # Hygiene must NOT run StatisticalPerturber. Vocabulary telltales
        # like "delve" should pass through unchanged.
        original = "We need to delve into the crucial aspects."
        result = run_aphanis(
            ["scrub-text", "--i-own-this-content"],
            stdin=original,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("delve", result.stdout)
        self.assertIn("crucial", result.stdout)

    def test_empty_input(self):
        result = run_aphanis(["scrub-text", "--i-own-this-content"], stdin="")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(result.stdout, "")

    def test_inline_text_argument(self):
        result = run_aphanis(
            ["scrub-text", "--i-own-this-content", "hello world"],
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("hello", result.stdout)
        self.assertIn("world", result.stdout)


class TestScrubTextConfirmation(unittest.TestCase):
    """scrub-text must require --i-own-this-content."""

    def test_refuses_without_confirmation_stdin(self):
        result = run_aphanis(["scrub-text"], stdin="hello world")
        self.assertEqual(result.returncode, 2)
        self.assertIn("--i-own-this-content", result.stderr)
        self.assertEqual(result.stdout, "")

    def test_refuses_without_confirmation_arg(self):
        result = run_aphanis(["scrub-text", "hello world"])
        self.assertEqual(result.returncode, 2)
        self.assertIn("--i-own-this-content", result.stderr)
        self.assertEqual(result.stdout, "")

    def test_refusal_message_mentions_what_it_does(self):
        result = run_aphanis(["scrub-text"], stdin="hi")
        self.assertIn("Unicode", result.stderr)
        # And explicitly states it does NOT humanize/perturb
        self.assertIn("NOT humanize", result.stderr)


class TestScrubFileHygiene(unittest.TestCase):
    """scrub-file must strip metadata + invisible Unicode, not humanize or pixel-jitter."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmp, ignore_errors=True)

    def _write(self, name, content):
        path = os.path.join(self.tmp, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path

    def test_text_file_zwsp_stripped(self):
        path = self._write("zw.txt", f"Hello world{ZWJ}with{ZWNJ}zero{BOM}width chars.\n")
        result = run_aphanis(["scrub-file", "--i-own-this-content", path])
        self.assertEqual(result.returncode, 0, result.stderr)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertNotIn(ZWSP, content)
        self.assertNotIn(ZWNJ, content)
        self.assertNotIn(ZWJ, content)
        self.assertNotIn(BOM, content)
        self.assertIn("Hello world", content)
        self.assertIn("with", content)
        self.assertIn("zero", content)
        self.assertIn("width", content)

    def test_text_file_ai_comment_stripped(self):
        path = self._write("code.py", "# Generated by Claude\ndef hello(): return 1\n")
        result = run_aphanis(["scrub-file", "--i-own-this-content", path])
        self.assertEqual(result.returncode, 0, result.stderr)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertNotIn("Generated by Claude", content)
        self.assertIn("def hello()", content)

    def test_text_file_does_not_humanize(self):
        # Hygiene path: text content of a file should not be humanized
        path = self._write("x.md", "Furthermore, we must consider this.\n")
        result = run_aphanis(["scrub-file", "--i-own-this-content", path])
        self.assertEqual(result.returncode, 0, result.stderr)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn("Furthermore", content)
        self.assertIn("we must", content)

    def test_docx_metadata_cleared(self):
        import docx
        path = os.path.join(self.tmp, "test.docx")
        doc = docx.Document()
        doc.core_properties.author = "Claude"
        doc.core_properties.comments = "Generated by Claude"
        doc.core_properties.keywords = "AI"
        doc.core_properties.subject = "watermark test"
        doc.core_properties.title = "t"
        doc.add_paragraph("Hello world.")
        doc.save(path)

        result = run_aphanis(["scrub-file", "--i-own-this-content", path])
        self.assertEqual(result.returncode, 0, result.stderr)

        doc2 = docx.Document(path)
        cp = doc2.core_properties
        self.assertEqual(cp.author, "")
        self.assertEqual(cp.comments, "")
        self.assertEqual(cp.keywords, "")
        self.assertEqual(cp.subject, "")
        self.assertEqual(cp.title, "")
        self.assertEqual(doc2.paragraphs[0].text, "Hello world.")

    def test_missing_file(self):
        path = os.path.join(self.tmp, "does_not_exist.txt")
        result = run_aphanis(["scrub-file", "--i-own-this-content", path])
        self.assertEqual(result.returncode, 1)
        self.assertIn("not found", result.stderr.lower())


class TestScrubFileConfirmation(unittest.TestCase):
    """scrub-file must require --i-own-this-content."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.path = os.path.join(self.tmp, "x.txt")
        with open(self.path, "w") as f:
            f.write("hello")

    def tearDown(self):
        import shutil
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_refuses_without_confirmation(self):
        result = run_aphanis(["scrub-file", self.path])
        self.assertEqual(result.returncode, 2)
        self.assertIn("--i-own-this-content", result.stderr)
        # File unchanged
        with open(self.path, "r") as f:
            self.assertEqual(f.read(), "hello")


class TestScrubPythonAPI(unittest.TestCase):
    """The Python API: clean_text with the hygiene-only flags."""

    def test_clean_text_no_humanize_no_perturb(self):
        text = "Furthermore, we must delve into this crucial testament."
        out = clean_text(
            text,
            perturb_stats=False,
            clean_ai_comments=True,
            mode=None,
            humanize=False,
        )
        self.assertIn("delve", out)
        self.assertIn("crucial", out)
        self.assertIn("Furthermore", out)
        # Hygiene does not rewrite
        self.assertNotIn("we've got to", out)
        self.assertNotIn("explore", out)  # perturb would have swapped delve -> explore

    def test_clean_text_strips_ai_comments(self):
        text = "# Generated by Claude\nhello"
        out = clean_text(text, humanize=False, perturb_stats=False)
        self.assertNotIn("Generated by Claude", out)
        self.assertIn("hello", out)

    def test_clean_text_strips_zwsp(self):
        text = f"ab{ZWJ}cd{ZWNJ}ef{BOM}gh"
        out = clean_text(text, humanize=False, perturb_stats=False)
        self.assertNotIn(ZWSP, out)
        self.assertNotIn(ZWNJ, out)
        self.assertNotIn(ZWJ, out)
        self.assertNotIn(BOM, out)
        self.assertEqual(out, "abcdefgh")


if __name__ == "__main__":
    unittest.main()
