"""
Tests for aphanis.provenance — the Honest Provenance Record generator.

These tests cover the verdict classifier, signature round-trip, and the
verify path on tampered/malformed records.
"""

import json
import unittest

from aphanis.provenance import (
    ProvenanceRecord,
    verify_provenance_record,
    record_to_text,
    VERDICT_NO_SIGNALS,
    VERDICT_INVISIBLE_UNICODE,
    VERDICT_AI_COMMENTS,
    VERDICT_AI_VOCAB,
    VERDICT_STRONGLY_ATTRIBUTED,
    VERDICT_MIXED,
)


class TestProvenanceVerdicts(unittest.TestCase):

    def test_clean_text_yields_no_signals(self):
        text = "Hello world, this is a normal sentence about gardening and rain."
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_NO_SIGNALS)
        self.assertEqual(record["signals"]["unicode"]["zero_width"], 0)
        self.assertEqual(record["signals"]["unicode"]["bidi_overrides"], 0)
        self.assertEqual(record["signals"]["em_dashes"], 0)
        self.assertEqual(len(record["signals"]["ai_attribution_comments"]), 0)
        self.assertEqual(len(record["signals"]["ai_vocabulary_signals"]), 0)

    def test_invisible_unicode_only(self):
        # Zero-width joiner between words
        text = "Hello‍world​with‌invisible﻿markers."
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_INVISIBLE_UNICODE)
        self.assertGreater(record["signals"]["unicode"]["zero_width"], 0)

    def test_bidi_overrides_count_as_invisible_unicode(self):
        text = "Hello ‮world‬ here."
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_INVISIBLE_UNICODE)
        self.assertGreater(record["signals"]["unicode"]["bidi_overrides"], 0)

    def test_ai_comment_only(self):
        text = "# Generated by Claude\ndef hello():\n    return 1\n"
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_AI_COMMENTS)
        self.assertEqual(len(record["signals"]["ai_attribution_comments"]), 1)

    def test_ai_vocabulary_only(self):
        text = (
            "Furthermore, we must delve into this crucial testament, "
            "tapestry of ideas, leveraging the realm of robust holistic interplay. "
            "In conclusion, the spearhead approach proves pivotal and paramount."
        )
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_AI_VOCAB)
        self.assertGreater(len(record["signals"]["ai_vocabulary_signals"]), 0)

    def test_unicode_plus_comments_strongly_attributed(self):
        text = "# Generated by Claude\ninvisible‍word here"
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_STRONGLY_ATTRIBUTED)

    def test_comments_plus_vocab_strongly_attributed(self):
        text = (
            "# Generated by Claude\n"
            "Furthermore, we must delve into this crucial testament, "
            "tapestry of ideas, spearhead this pivotal journey."
        )
        record = ProvenanceRecord(text).generate()
        self.assertEqual(record["verdict"], VERDICT_STRONGLY_ATTRIBUTED)


class TestProvenanceSignature(unittest.TestCase):

    def test_signature_round_trip(self):
        text = "Hello world."
        record = ProvenanceRecord(text).generate()
        result = verify_provenance_record(record)
        self.assertEqual(result["status"], "VALID")
        self.assertEqual(result["record_id"], record["record_id"])
        self.assertEqual(result["verdict"], record["verdict"])

    def test_tampered_verdict_detected(self):
        # Use a sample that produces a non-trivial verdict, then tamper.
        text = "# Generated by Claude\nhello"
        record = ProvenanceRecord(text).generate()
        self.assertNotEqual(record["verdict"], VERDICT_NO_SIGNALS)
        tampered = dict(record)
        tampered["verdict"] = VERDICT_NO_SIGNALS
        result = verify_provenance_record(tampered)
        self.assertEqual(result["status"], "TAMPERED")

    def test_tampered_input_hash_detected(self):
        text = "Hello world."
        record = ProvenanceRecord(text).generate()
        tampered = dict(record)
        tampered["input_sha256"] = "0" * 64
        result = verify_provenance_record(tampered)
        self.assertEqual(result["status"], "TAMPERED")

    def test_missing_fields_reported(self):
        result = verify_provenance_record({"record_id": "X"})
        self.assertEqual(result["status"], "MISSING_FIELDS")
        self.assertIn("verdict", result["missing"])
        self.assertIn("signals", result["missing"])

    def test_empty_record_reports_missing(self):
        result = verify_provenance_record({})
        self.assertEqual(result["status"], "MISSING_FIELDS")

    def test_signature_is_deterministic(self):
        # Same input text on the same node should produce a different record_id
        # (since record_id is random), but the input_sha256 field is the
        # content-addressed part. We test that.
        text = "Hello world."
        a = ProvenanceRecord(text).generate()
        b = ProvenanceRecord(text).generate()
        self.assertEqual(a["input_sha256"], b["input_sha256"])
        self.assertNotEqual(a["record_id"], b["record_id"])


class TestProvenanceRendering(unittest.TestCase):

    def test_text_rendering_contains_verdict(self):
        text = "Hello​world"
        record = ProvenanceRecord(text).generate()
        rendered = record_to_text(record)
        self.assertIn(record["record_id"], rendered)
        self.assertIn("Verdict", rendered)
        self.assertIn(VERDICT_INVISIBLE_UNICODE, rendered)

    def test_text_rendering_handles_missing_fields(self):
        rendered = record_to_text({})
        self.assertIn("Verdict", rendered)
        self.assertIn("?", rendered)  # record_id is unknown


class TestProvenanceInputs(unittest.TestCase):

    def test_empty_string_is_no_signals(self):
        record = ProvenanceRecord("").generate()
        self.assertEqual(record["verdict"], VERDICT_NO_SIGNALS)
        self.assertEqual(record["input_length_words"], 0)

    def test_whitespace_only_is_no_signals(self):
        record = ProvenanceRecord("   \n\n  \t  ").generate()
        self.assertEqual(record["verdict"], VERDICT_NO_SIGNALS)

    def test_source_name_default(self):
        record = ProvenanceRecord("hello").generate()
        self.assertEqual(record["source_name"], "Input Text")

    def test_source_name_custom(self):
        record = ProvenanceRecord("hello", source_name="my-doc.txt").generate()
        self.assertEqual(record["source_name"], "my-doc.txt")

    def test_input_sha256_is_hex_64(self):
        record = ProvenanceRecord("hello world").generate()
        self.assertEqual(len(record["input_sha256"]), 64)
        int(record["input_sha256"], 16)  # raises if not hex

    def test_non_string_input_rejected(self):
        with self.assertRaises(TypeError):
            ProvenanceRecord(123)  # type: ignore[arg-type]

    def test_record_body_is_json_serializable(self):
        # The whole record should round-trip through json.dumps/loads.
        text = "Hello​ world with # Generated by Claude"
        record = ProvenanceRecord(text).generate()
        encoded = json.dumps(record, ensure_ascii=False)
        decoded = json.loads(encoded)
        self.assertEqual(decoded["record_id"], record["record_id"])
        # And the signature should still verify after a JSON round-trip.
        result = verify_provenance_record(decoded)
        self.assertEqual(result["status"], "VALID")


if __name__ == "__main__":
    unittest.main()
