import os
import tempfile
import unittest
from untrace.cleaner import UnicodeSanitizer, StatisticalPerturber, AICommentSanitizer, FileMetadataSanitizer, clean_text, clean_file


class TestUntraceAI(unittest.TestCase):

    def test_unicode_sanitizer_zero_width_and_emdash(self):
        dirty_text = "This\u200bis\u00ad a\u00a0test\ufeff string\ufe0f — with em-dashes and “smart quotes”."
        cleaned = UnicodeSanitizer.clean(dirty_text)
        self.assertNotIn("\u200b", cleaned)
        self.assertNotIn("\u00ad", cleaned)
        self.assertNotIn("\ufeff", cleaned)
        self.assertNotIn("\ufe0f", cleaned)
        self.assertNotIn("\u00a0", cleaned)
        self.assertNotIn("—", cleaned)
        self.assertNotIn("“", cleaned)
        self.assertNotIn("”", cleaned)
        self.assertIn('"smart quotes"', cleaned)

    def test_ai_comment_sanitizer(self):
        code_text = "# Generated by Claude\ndef hello():\n    # Modified by AI\n    return 'world'\n"
        cleaned = AICommentSanitizer.clean(code_text)
        self.assertNotIn("Generated by Claude", cleaned)
        self.assertNotIn("Modified by AI", cleaned)
        self.assertIn("def hello():", cleaned)

    def test_statistical_perturber(self):
        ai_text = "Furthermore, we must delve into this crucial testament, tapestry of ideas, and paramount landscape."
        perturbed = StatisticalPerturber.perturb(ai_text)
        self.assertNotIn("delve", perturbed.lower())
        self.assertNotIn("crucial", perturbed.lower())
        self.assertNotIn("testament", perturbed.lower())
        self.assertNotIn("tapestry", perturbed.lower())
        self.assertNotIn("paramount", perturbed.lower())
        self.assertIn("explore", perturbed.lower())
        self.assertIn("important", perturbed.lower())

    def test_clean_text_helper(self):
        dirty_text = "# Generated by Claude\nDelve\u200b into crucial\ufeff matters — today."
        cleaned = clean_text(dirty_text, perturb_stats=True)
        self.assertNotIn("\u200b", cleaned)
        self.assertNotIn("\ufeff", cleaned)
        self.assertNotIn("Generated by Claude", cleaned)
        self.assertNotIn("delve", cleaned.lower())
        self.assertIn("explore", cleaned.lower())

    def test_file_cleaner_markdown(self):
        with tempfile.NamedTemporaryFile(suffix=".md", mode="w+", delete=False) as f:
            f.write("<!-- AI comment watermark -->\n# Title\u200b\nDelve into details.")
            temp_path = f.name

        try:
            success, msg = clean_file(temp_path)
            self.assertTrue(success)
            with open(temp_path, "r", encoding="utf-8") as f:
                content = f.read()
            self.assertNotIn("<!-- AI comment watermark -->", content)
            self.assertNotIn("\u200b", content)
        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)

    def test_file_cleaner_svg(self):
        svg_content = '<svg><metadata>C2PA Signature</metadata><!-- Comment --><g data-c2pa="true"></g></svg>'
        with tempfile.NamedTemporaryFile(suffix=".svg", mode="w+", delete=False) as f:
            f.write(svg_content)
            temp_path = f.name

        try:
            success, msg = clean_file(temp_path)
            self.assertTrue(success)
            with open(temp_path, "r", encoding="utf-8") as f:
                content = f.read()
            self.assertNotIn("<metadata>", content)
            self.assertNotIn("<!-- Comment -->", content)
            self.assertNotIn('data-c2pa="true"', content)
        finally:
            if os.path.exists(temp_path):
                os.remove(temp_path)

    def test_audit_text(self):
        from untrace.cleaner import audit_text
        clean_report = audit_text("Simple human sentence.")
        self.assertEqual(clean_report["status"], "CLEAN")
        self.assertEqual(clean_report["score"], 100)

        dirty_report = audit_text("Delve into crucial matters — today.")
        self.assertEqual(dirty_report["status"], "WATERMARKED_OR_TELLTALES_DETECTED")
        self.assertTrue(len(dirty_report["issues"]) > 0)


if __name__ == "__main__":
    unittest.main()
