import unittest
from aphanis.stealth import StealthProfile, StealthMode, StegoRiskMatrix


class TestStealthEngine(unittest.TestCase):

    def test_stealth_profiles(self):
        paranoid = StealthProfile(StealthMode.PARANOID)
        self.assertTrue(paranoid.clean_unicode)
        self.assertTrue(paranoid.clean_punctuation)
        self.assertTrue(paranoid.clean_ai_comments)
        self.assertTrue(paranoid.perturb_stats)
        self.assertTrue(paranoid.disrupt_image_jitter)

        minimal = StealthProfile(StealthMode.MINIMAL)
        self.assertTrue(minimal.clean_unicode)
        self.assertFalse(minimal.clean_punctuation)
        self.assertFalse(minimal.clean_ai_comments)
        self.assertFalse(minimal.perturb_stats)
        self.assertFalse(minimal.disrupt_image_jitter)

    def test_stego_risk_matrix_evaluation(self):
        dirty_text = "# Generated by Claude\nDelve\u200b into crucial\ufeff matters — today."
        matrix = StegoRiskMatrix.evaluate(dirty_text)

        self.assertIn("overall_clean_score", matrix)
        self.assertIn("provenance_risk_level", matrix)
        self.assertIn("vectors", matrix)

        vectors = matrix["vectors"]
        self.assertIn("vector_1_unicode_steganography", vectors)
        self.assertIn("vector_2_statistical_model", vectors)
        self.assertIn("vector_3_metadata_container", vectors)
        self.assertIn("vector_4_spatial_frequency", vectors)

        self.assertGreater(vectors["vector_1_unicode_steganography"]["risk_score"], 0.0)
        self.assertGreater(vectors["vector_2_statistical_model"]["risk_score"], 0.0)

    def test_clean_text_with_mode(self):
        from aphanis.cleaner import clean_text
        dirty_text = "Delve\u200b into crucial matters — today."
        clean_paranoid = clean_text(dirty_text, mode=StealthMode.PARANOID)
        self.assertNotIn("\u200b", clean_paranoid)
        self.assertNotIn("delve", clean_paranoid.lower())
        self.assertIn("explore", clean_paranoid.lower())


if __name__ == "__main__":
    unittest.main()
