name: 🐛 Bug Report
description: Create a report to help us improve Aphanis
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: input
    id: environment
    attributes:
      label: Environment Info
      description: OS version, Python version, Aphanis version (`aphanis --version`).
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
