name: 🚀 Feature Request
description: Suggest an idea or feature for Aphanis
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Tell us about the feature you'd like to see in Aphanis!
  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Is your feature request related to a problem or new use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
    validations:
      required: true
