"""
Untrace AI - Ultimate AI Provenance, Watermark, Comment & Metadata Sanitization Module.
"""

import os
import re
import random
import unicodedata
from typing import Tuple, Dict, Any, Optional, List


class UnicodeSanitizer:
    """Strips hidden zero-width spaces, tracking tags, variation selectors, homoglyphs, and punctuation telltales."""

    # Complete zero-width & invisible characters used for steganography / LLM watermarking
    ZERO_WIDTH_CHARS = {
        '\u200B': 'Zero-Width Space',
        '\u200C': 'Zero-Width Non-Joiner',
        '\u200D': 'Zero-Width Joiner',
        '\uFEFF': 'Zero-Width No-Break Space (BOM)',
        '\u2060': 'Word Joiner',
        '\u2061': 'Function Application',
        '\u2062': 'Invisible Times',
        '\u2063': 'Invisible Separator',
        '\u2064': 'Invisible Plus',
        '\u00AD': 'Soft Hyphen',
        '\u180E': 'Mongolian Vowel Separator',
    }

    # Bidi & direction override characters
    BIDI_CHARS = {
        '\u200E': 'Left-to-Right Mark',
        '\u200F': 'Right-to-Left Mark',
        '\u202A': 'Left-to-Right Embedding',
        '\u202B': 'Right-to-Left Embedding',
        '\u202C': 'Pop Directional Formatting',
        '\u202D': 'Left-to-Right Override',
        '\u202E': 'Right-to-Left Override',
        '\u2066': 'Left-to-Right Isolate',
        '\u2067': 'Right-to-Left Isolate',
        '\u2068': 'First Strong Isolate',
        '\u2069': 'Pop Directional Isolate'
    }

    # Custom space normalization
    SPACE_NORMALIZATIONS = {
        '\u00A0': 'Non-breaking space',
        '\u2002': 'En space',
        '\u2003': 'Em space',
        '\u2004': 'Three-per-em space',
        '\u2005': 'Four-per-em space',
        '\u2006': 'Six-per-em space',
        '\u2007': 'Figure space',
        '\u2008': 'Punctuation space',
        '\u2009': 'Thin space',
        '\u200A': 'Hair space',
        '\u202F': 'Narrow no-break space',
        '\u205F': 'Medium mathematical space',
        '\u3000': 'Ideographic space',
    }

    # Punctuation homoglyphs & LLM formatting telltales
    PUNCTUATION_REPLACEMENTS = {
        '“': '"',  # Left double smart quote
        '”': '"',  # Right double smart quote
        '‘': "'",  # Left single smart quote
        '’': "'",  # Right single smart quote
        '—': ' - ', # Em-dash (Claude signature telltale) -> space-hyphen-space
        '–': '-',  # En-dash -> standard hyphen
        '…': '...',# Ellipsis character -> three dots
    }

    @classmethod
    def clean(cls, text: str, normalize_unicode: bool = True, clean_punctuation: bool = True) -> str:
        """Strips invisible watermarking characters, variation selectors, normalizes quotes/dashes & Unicode."""
        if not text:
            return ""

        # 1. Remove Tag Characters (\uE0001 - \uE007F) & Variation Selectors (\uFE00 - \uFE0F, \uE0100 - \uE01EF)
        cleaned_chars = []
        for c in text:
            code = ord(c)
            if 0xE0001 <= code <= 0xE007F:
                continue
            if 0xFE00 <= code <= 0xFE0F or 0xE0100 <= code <= 0xE01EF:
                continue
            cleaned_chars.append(c)

        text = "".join(cleaned_chars)

        # 2. Filter zero-width & bidi characters, normalize non-standard space codes
        chars = []
        for char in text:
            if char in cls.ZERO_WIDTH_CHARS or char in cls.BIDI_CHARS:
                continue
            if char in cls.SPACE_NORMALIZATIONS:
                chars.append(' ')
            elif clean_punctuation and char in cls.PUNCTUATION_REPLACEMENTS:
                chars.append(cls.PUNCTUATION_REPLACEMENTS[char])
            else:
                chars.append(char)
        text = "".join(chars)

        # 3. Unicode NFKC Normalization
        if normalize_unicode:
            text = unicodedata.normalize("NFKC", text)

        # 4. Clean consecutive space artifacts created by stripping
        text = re.sub(r'[ \t]+', ' ', text)
        
        # 5. Remove trailing space per line
        lines = [line.rstrip() for line in text.splitlines()]
        return "\n".join(lines)


class AICommentSanitizer:
    """Strips AI code comments, watermarks, and generated header annotations."""

    SINGLE_LINE_PATTERNS = [
        r'#\s*(?:Generated by|Created by|Co-authored-by:|Modified by|AI-generated|Claude|ChatGPT|LLM).*',
        r'//\s*(?:Generated by|Created by|Co-authored-by:|Modified by|AI-generated|Claude|ChatGPT|LLM).*',
        r'@generated.*',
    ]

    MULTI_LINE_PATTERNS = [
        r'/\*\s*(?:Generated by|Created by|Co-authored-by:|Modified by|AI-generated|Claude|ChatGPT|LLM).*?\*/',
        r'<!--\s*(?:Generated by|Created by|Co-authored-by:|Modified by|AI-generated|Claude|ChatGPT|LLM).*?-->',
    ]

    @classmethod
    def clean(cls, text: str) -> str:
        """Removes AI signatures and generated code comments."""
        if not text:
            return ""

        result = text
        for pattern in cls.SINGLE_LINE_PATTERNS:
            result = re.sub(pattern, '', result, flags=re.IGNORECASE)

        for pattern in cls.MULTI_LINE_PATTERNS:
            result = re.sub(pattern, '', result, flags=re.IGNORECASE | re.DOTALL)
        
        # Remove empty comment lines
        lines = [line for line in result.splitlines() if line.strip() != '' or line == '']
        return "\n".join(lines)


class StatisticalPerturber:
    """Perturbs text to disrupt n-gram statistical AI watermarks and Claude-specific vocabulary telltales."""

    AI_VOCAB_SWAPS = {
        r'\bdelve\b': 'explore',
        r'\bdelves\b': 'explores',
        r'\bdelving\b': 'exploring',
        r'\btestament\b': 'proof',
        r'\btestaments\b': 'proofs',
        r'\bspearhead\b': 'lead',
        r'\bspearheaded\b': 'led',
        r'\bspearheading\b': 'leading',
        r'\bfostering\b': 'building',
        r'\bfoster\b': 'encourage',
        r'\bcrucial\b': 'important',
        r'\bpivotal\b': 'key',
        r'\bparamount\b': 'essential',
        r'\bmultifaceted\b': 'complex',
        r'\bunderscores\b': 'highlights',
        r'\bunderscore\b': 'highlight',
        r'\bseamlessly\b': 'smoothly',
        r'\bseamless\b': 'smooth',
        r'\bgame-changer\b': 'breakthrough',
        r'\btapestry\b': 'blend',
        r'\bbeacon\b': 'symbol',
        r'\bnestled\b': 'situated',
        r'\bunwavering\b': 'steady',
        r'\bever-evolving\b': 'developing',
        r'\brealm\b': 'area',
        r'\bresonate\b': 'align',
        r'\bharness\b': 'use',
        r'\bleverage\b': 'utilize',
        r'\bparadigm shift\b': 'fundamental change',
        r'\bshed light\b': 'explain',
        r'\binterplay\b': 'interaction',
        r'\bindispensable\b': 'vital',
        r'\bvibrant\b': 'lively',
        r'\bsynergy\b': 'collaboration',
        r'\bembark\b': 'begin',
        r'\bmeticulous\b': 'thorough',
        r'\bmeticulously\b': 'carefully',
        r'\bnotably\b': 'specifically',
        r'\bimportantly\b': 'note that',
        r'\bconsequently\b': 'thus',
        r'\binvaluable\b': 'helpful',
        r'\btransformative\b': 'major',
        r'\blandscape\b': 'environment',
        r'\bcornerstone\b': 'foundation',
        r'\blinchpin\b': 'core',
        r'\bsynergistic\b': 'combined',
        r'\bunderpin\b': 'support',
        r'\bunderpins\b': 'supports',
        r'\bin conclusion\b': 'to summarize',
        r'\bfurthermore\b': 'also',
        r'\bmoreover\b': 'additionally',
        r'\bnevertheless\b': 'however',
        r'\bit is important to note that\b': 'note that',
        r'\bit is worth noting that\b': 'note that',
        r'\bit is crucial to\b': 'remember to',
        r'\bin summary\b': 'overall',
        r'\bmoving forward\b': 'next',
        r'\brich tapestry\b': 'wide range',
        r'\ba myriad of\b': 'many',
        r'\ba wide array of\b': 'many',
        r'\bboasts a\b': 'has a',
        r'\bserves as a\b': 'is a',
        r'\btakes center stage\b': 'is central',
    }

    @classmethod
    def perturb(cls, text: str) -> str:
        """Replaces common statistical AI marker phrases with natural alternatives while preserving case."""
        if not text:
            return ""

        result = text
        for pattern, replacement in cls.AI_VOCAB_SWAPS.items():
            def _replace(match):
                word = match.group(0)
                if word.istitle():
                    return replacement.capitalize()
                elif word.isupper():
                    return replacement.upper()
                return replacement

            result = re.sub(pattern, _replace, result, flags=re.IGNORECASE)

        return result


class ImageWatermarkDisrupter:
    """Modulates image LSB pixel noise to disrupt frequency-domain spatial watermarks."""

    @classmethod
    def perturb_image(cls, file_path: str, jitter: bool = True) -> Tuple[bool, str]:
        """Strips EXIF/C2PA metadata and applies perceptual sub-pixel noise jitter."""
        try:
            from PIL import Image
            img = Image.open(file_path)
            mode = img.mode
            size = img.size
            pixels = list(img.getdata())

            if jitter and mode in ('RGB', 'RGBA'):
                new_pixels = []
                for p in pixels:
                    if mode == 'RGB':
                        r, g, b = p
                        r = max(0, min(255, r + random.choice([-1, 0, 1])))
                        new_pixels.append((r, g, b))
                    else:
                        r, g, b, a = p
                        r = max(0, min(255, r + random.choice([-1, 0, 1])))
                        new_pixels.append((r, g, b, a))
                pixels = new_pixels

            img_cleaned = Image.new(mode, size)
            img_cleaned.putdata(pixels)
            img_cleaned.save(file_path)
            return True, f"Stripped metadata & perturbed spatial watermarks for {file_path}"
        except Exception as e:
            return False, f"Failed to process image: {str(e)}"


class AuditTool:
    """Audits text and files for invisible zero-width watermarks, C2PA signatures, and AI telltales."""

    @classmethod
    def audit_text(cls, text: str) -> Dict[str, Any]:
        """Scans text for zero-width characters, em-dashes, AI comments, and telltale phrases."""
        if not text:
            return {"status": "CLEAN", "score": 100, "issues": []}

        issues = []
        zero_width_count = 0
        bidi_count = 0
        tag_char_count = 0
        em_dash_count = text.count('—')
        smart_quote_count = text.count('“') + text.count('”') + text.count('‘') + text.count('’')

        for c in text:
            code = ord(c)
            if c in UnicodeSanitizer.ZERO_WIDTH_CHARS:
                zero_width_count += 1
            if c in UnicodeSanitizer.BIDI_CHARS:
                bidi_count += 1
            if 0xE0001 <= code <= 0xE007F or 0xFE00 <= code <= 0xFE0F:
                tag_char_count += 1

        if zero_width_count > 0:
            issues.append(f"Found {zero_width_count} hidden zero-width / invisible tracking characters")
        if bidi_count > 0:
            issues.append(f"Found {bidi_count} directionality / bidi override characters")
        if tag_char_count > 0:
            issues.append(f"Found {tag_char_count} tag / variation selector tracking markers")
        if em_dash_count > 0:
            issues.append(f"Found {em_dash_count} em-dash ('—') AI telltale signatures")
        if smart_quote_count > 0:
            issues.append(f"Found {smart_quote_count} smart/curved quote telltales")

        # Search for AI vocabulary telltales
        telltale_words_found = []
        for pattern in StatisticalPerturber.AI_VOCAB_SWAPS.keys():
            matches = re.findall(pattern, text, flags=re.IGNORECASE)
            if matches:
                telltale_words_found.extend(matches)

        if telltale_words_found:
            issues.append(f"Found {len(telltale_words_found)} AI vocabulary telltales: {', '.join(set(telltale_words_found[:5]))}")

        # Check AI comment signatures
        comment_matches = []
        for pattern in AICommentSanitizer.SINGLE_LINE_PATTERNS + AICommentSanitizer.MULTI_LINE_PATTERNS:
            matches = re.findall(pattern, text, flags=re.IGNORECASE)
            if matches:
                comment_matches.extend(matches)
        if comment_matches:
            issues.append(f"Found {len(comment_matches)} AI code comment signatures")

        is_clean = (len(issues) == 0)
        return {
            "status": "CLEAN" if is_clean else "WATERMARKED_OR_TELLTALES_DETECTED",
            "score": 100 if is_clean else max(0, 100 - (len(issues) * 20)),
            "issues": issues
        }


class FileMetadataSanitizer:
    """Strips EXIF, C2PA, XMP, comments, and tracking metadata from files."""

    @classmethod
    def clean_markdown_or_text(cls, content: str) -> str:
        """Removes HTML comments, AI code comments, and cleans Unicode in Markdown/Text files."""
        cleaned = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL)
        cleaned = AICommentSanitizer.clean(cleaned)
        return UnicodeSanitizer.clean(cleaned)

    @classmethod
    def clean_svg(cls, content: str) -> str:
        """Removes <metadata>, C2PA attributes, and XML comments from SVG."""
        cleaned = re.sub(r'<metadata.*?>.*?</metadata>', '', content, flags=re.DOTALL | re.IGNORECASE)
        cleaned = re.sub(r'<!--.*?-->', '', cleaned, flags=re.DOTALL)
        cleaned = re.sub(r'\s+data-(c2pa|provenance|watermark|ai|claude)="[^"]*"', '', cleaned, flags=re.IGNORECASE)
        return UnicodeSanitizer.clean(cleaned)

    @classmethod
    def clean_html(cls, content: str) -> str:
        """Removes meta tags, comments, and zero-width characters in HTML."""
        cleaned = re.sub(r'<!--.*?-->', '', content, flags=re.DOTALL)
        cleaned = re.sub(r'<meta\s+name=["\'](c2pa|provenance|generator|ai-watermark|claude)["\'].*?>', '', cleaned, flags=re.IGNORECASE)
        return UnicodeSanitizer.clean(cleaned)

    @classmethod
    def clean_file(cls, file_path: str, disrupt_image_pixels: bool = False, perturb_stats: bool = False) -> Tuple[bool, str]:
        """Detects file type and cleans watermarks, AI comments, and metadata."""
        if not os.path.exists(file_path):
            return False, f"File not found: {file_path}"

        ext = os.path.splitext(file_path)[1].lower()

        try:
            if ext in ['.md', '.txt', '.py', '.js', '.ts', '.jsx', '.tsx', '.json', '.yaml', '.yml', '.css']:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                cleaned = cls.clean_markdown_or_text(content)
                if perturb_stats:
                    cleaned = StatisticalPerturber.perturb(cleaned)
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(cleaned)
                return True, f"Sanitized code/text file: {file_path}"

            elif ext == '.svg':
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                cleaned = cls.clean_svg(content)
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(cleaned)
                return True, f"Sanitized SVG file: {file_path}"

            elif ext in ['.html', '.htm']:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                cleaned = cls.clean_html(content)
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(cleaned)
                return True, f"Sanitized HTML file: {file_path}"

            elif ext in ['.png', '.jpg', '.jpeg']:
                return ImageWatermarkDisrupter.perturb_image(file_path, jitter=disrupt_image_pixels)

            elif ext == '.pdf':
                try:
                    from pypdf import PdfReader, PdfWriter
                    reader = PdfReader(file_path)
                    writer = PdfWriter()
                    for page in reader.pages:
                        writer.add_page(page)
                    with open(file_path, 'wb') as f:
                        writer.write(f)
                    return True, f"Cleared PDF metadata & annotations: {file_path}"
                except Exception as e:
                    return False, f"PDF cleaning failed: {str(e)}"

            elif ext == '.docx':
                try:
                    import docx
                    doc = docx.Document(file_path)
                    cp = doc.core_properties
                    cp.author = ""
                    cp.comments = ""
                    cp.keywords = ""
                    cp.subject = ""
                    cp.title = ""
                    for p in doc.paragraphs:
                        p.text = UnicodeSanitizer.clean(p.text)
                    doc.save(file_path)
                    return True, f"Sanitized DOCX core properties & paragraphs: {file_path}"
                except Exception as e:
                    return False, f"DOCX cleaning failed: {str(e)}"

            else:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                cleaned = UnicodeSanitizer.clean(content)
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(cleaned)
                return True, f"Sanitized raw file: {file_path}"

        except Exception as e:
            return False, f"Error processing file {file_path}: {str(e)}"


def clean_text(text: str, perturb_stats: bool = False, clean_ai_comments: bool = True) -> str:
    """Helper function to clean raw text from zero-width watermarks, AI comments, and optional statistical markers."""
    cleaned = UnicodeSanitizer.clean(text)
    if clean_ai_comments:
        cleaned = AICommentSanitizer.clean(cleaned)
    if perturb_stats:
        cleaned = StatisticalPerturber.perturb(cleaned)
    return cleaned


def clean_file(file_path: str, disrupt_image_pixels: bool = False, perturb_stats: bool = False) -> Tuple[bool, str]:
    """Helper function to clean file metadata and watermarks."""
    return FileMetadataSanitizer.clean_file(file_path, disrupt_image_pixels=disrupt_image_pixels, perturb_stats=perturb_stats)


def audit_text(text: str) -> Dict[str, Any]:
    """Audits input text for zero-width characters, AI comments, em-dashes, and telltales."""
    return AuditTool.audit_text(text)
