"""
Untrace AI - Custom Rule Engine.
Enables user-defined rule configurations (.untracerules.json) for custom zero-width characters,
vocabulary blacklists/whitelists, regex replacements, and comment patterns.
"""

import json
import os
import re
from typing import Dict, Any, List, Optional


DEFAULT_STARTER_RULES: Dict[str, Any] = {
    "version": "1.0",
    "name": "Default Custom Untrace Rules",
    "description": "User-defined custom rules for Untrace AI sanitization.",
    "custom_zero_width_chars": [
        "\\u200B",
        "\\uFEFF",
        "\\u2060"
    ],
    "custom_word_swaps": {
        "furthermore": "also",
        "nevertheless": "however",
        "spearhead": "lead",
        "testament": "proof"
    },
    "custom_regex_replacements": [
        {
            "pattern": "\\bIn summary,",
            "replacement": "Overall,"
        },
        {
            "pattern": "\\bIt is essential to\\b",
            "replacement": "Remember to"
        }
    ],
    "custom_ai_comment_patterns": [
        "#\\s*AI-authored.*",
        "//\\s*Generated by.*"
    ]
}


class RuleEngine:
    """Loads and applies custom user rules (.untracerules.json)."""

    def __init__(self, rules_data: Optional[Dict[str, Any]] = None):
        self.rules_data = rules_data or {}

    @classmethod
    def from_file(cls, filepath: str) -> "RuleEngine":
        """Loads a RuleEngine instance from a JSON configuration file."""
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"Rules configuration file not found: {filepath}")

        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)

        return cls(data)

    @staticmethod
    def create_starter_rules_file(filepath: str = ".untracerules.json", overwrite: bool = False) -> str:
        """Generates a template .untracerules.json starter configuration file."""
        if os.path.exists(filepath) and not overwrite:
            return f"Rules file already exists at {filepath}"

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(DEFAULT_STARTER_RULES, f, indent=2)

        return f"Created starter rules file at {filepath}"

    def apply_rules(self, text: str) -> str:
        """Applies loaded custom rules to the given text."""
        if not text or not self.rules_data:
            return text

        result = text

        # 1. Custom Zero-Width Character Stripping
        zero_width_chars = self.rules_data.get("custom_zero_width_chars", [])
        for char_spec in zero_width_chars:
            try:
                # Handle unicode escape strings like "\\u200B"
                char_str = json.loads(f'"{char_spec}"') if char_spec.startswith('\\u') else char_spec
                result = result.replace(char_str, '')
            except Exception:
                result = result.replace(char_spec, '')

        # 2. Custom Word Swaps
        word_swaps = self.rules_data.get("custom_word_swaps", {})
        for orig, swap in word_swaps.items():
            pattern = r'\b' + re.escape(orig) + r'\b'
            def _repl(m):
                word = m.group(0)
                if word.istitle():
                    return swap.capitalize()
                elif word.isupper():
                    return swap.upper()
                return swap
            result = re.sub(pattern, _repl, result, flags=re.IGNORECASE)

        # 3. Custom Regex Replacements
        regex_repls = self.rules_data.get("custom_regex_replacements", [])
        for item in regex_repls:
            pat = item.get("pattern")
            rep = item.get("replacement", "")
            if pat:
                result = re.sub(pat, rep, result, flags=re.IGNORECASE)

        # 4. Custom AI Comment Patterns
        comment_pats = self.rules_data.get("custom_ai_comment_patterns", [])
        for pat in comment_pats:
            result = re.sub(pat, '', result, flags=re.IGNORECASE)

        return result
